### ISSUE TITLE
begin research into Fedora 4

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#1]
_From @davidschober on June 10, 2016 14:43_

So developer developers without fedora 4 knowledge feel generally caught up. 

Done looks like

Developers feel like they can contribute to technical stories.
- [ ] Run through migration tool from previous sprint on local dev machine
- [ ] get latest version of jetty w/ fedora and solr on local dev machine

_Copied from original issue: avalonmediasystem/avalon#878_

**Comment by mcwhitaker** [comment]
@joncameron  - Jon, Could you please create the Sprint 102 milestone for this new repo (avalon-planning) so the milestone can be added to the story? Thank you.

**Comment by joncameron** [comment]
@mcwhitaker Done! David and I will keep both updated with the same milestones for our sprints.
