### ISSUE TITLE
Draft release and performance testing plans

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#104]
Draft a document to be presented to the team as a proposal for how to include performance testing, regression testing, release testing  as a more formal part of the development cycle.

**Comment by mcwhitaker** [comment]
[avalon-hyrax-boxes.xlsx](https://github.com/avalonmediasystem/avalon-planning/files/868032/avalon-hyrax-boxes.xlsx)

**Comment by Karthikeya212** [comment]
[Performance Indices.xlsx](https://github.com/avalonmediasystem/avalon-planning/files/920525/Performance.Indices.xlsx)

**Comment by mcwhitaker** [comment]
[Performance testing plan for Avalon.docx](https://github.com/avalonmediasystem/avalon-planning/files/922319/Performance.testing.plan.for.Avalon.docx)
