### ISSUE TITLE
Record Performance Metrics on Wiki

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#129]
### Description
As part of improving and benchmarking Avalon performance, we need baseline performance data from the current instance of Avalon on our Mallorn server.

### Done Looks Like
Performance metrics as specified in the document in the reference ticket, #1832, are recorded in the Avalon wiki for future benchmarking and reference.

### Tasks
- [ ] Create wiki space to store benchmarks, both for this and to store existing data currently in spreadsheets/github issues.

### Reference Ticket
#1832 - As a QA Analyst, I need performance parameter values set

**Comment by Karthikeya212** [comment]
wiki page created (system information still needs to be added) https://wiki.dlib.indiana.edu/display/VarVideo/Performance+Metrics

@joncameron @mcwhitaker  feel free to modify anything and move it to any preferred location
