### ISSUE TITLE
Community Work

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#233]

**Comment by cjcolvar** [comment]
For me:
Working on Hyrax 2.1.0 release including discussion, triaging, and submitting PRs for issues:
nurax#186
hyrax#2744
hyrax#2788
hyrax#2795
Helped with hyrax#2777
Code Stability WG
SIGAHR
Governance Proposal review and feedback

**Comment by adamjarling** [comment]
Worked on the following Hyrax items:

Accessibility 360 audit meetings
hyrax#2685
hyrax#2680
hyrax#2606
hyrax#2770
hyrax#2780
hyrax#2775

Worked with LaRita at Notre Dame troubleshooting a turbolinks redirect issue in Collections.

UX Interest Group Usability study 2.0 meetings and planning
