### ISSUE TITLE
Community Work - Sprint 148

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#238]

**Comment by adamjarling** [comment]
Here's what I'm working on for Hyrax-related:
samvera/hyrax#2619
Investigate and clear out samvera/hyrax#1678
Investigate and clear out samvera/hyrax#1512
Samvera UX Interest Group meeting / re-org reach outs: samvera/hyrax#1512
Accessibility Issues: pull from this list, ask about priority. https://github.com/curationexperts/nurax/issues?q=is%3Aissue+is%3Aopen+label%3Aaccessibility

**Comment by cjcolvar** [comment]
I'm currently working on hyrax#2815 which involves fixing byte range requests for hyrax's download controller.

**Comment by mcwhitaker** [comment]
@cjcolvar @phuongdh @carrickr @jlhardes @davidschober attended LDCX.
@carrickr attended Developer Congress
