### ISSUE TITLE
Community Work - Sprint 149

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#242]
#### Adam Arling
- https://github.com/samvera/hyrax/issues/2793
- https://wiki.duraspace.org/display/samvera/2018-04-05+Accessibility+Planning+Meeting+notes

**Comment by cjcolvar** [comment]
#### Chris Colvard
- [samvera/hyrax#2908](https://github.com/samvera/hyrax/pull/2908)
- Work on Hydra-Head pushing towards 10.5.1 release and planning for 11.0.0
- Hyrax 2.1.0.beta2 issue triaging and pull request reviewing
