### ISSUE TITLE
Investigation: Structural Metadata Editor Tooling

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#245]
### Description
This issue is for an investigation into libraries that can be used to display and manipulate waveforms and playback, looking specifically at waveform.js.

### Done Looks Like
- Investigation done into wavesurfer.js and other relevant libraries or tooling
- Notes written up about investigation with an eye to future work on this editor

child of https://github.com/samvera-labs/avalon-bundle/issues/177

**Comment by adamjarling** [comment]
Reference this implementation: https://www.soundslice.com/slices/xGfcc/

**Comment by phuongdh** [comment]
Wavesurfer.js [does not support HLS](https://github.com/katspaugh/wavesurfer.js/issues/1078) currently. It couldn't decode our derivative files either.

But it takes an array of peaks like `wavesurfer.load(file_path, peaks, preload, duration)`. A peaks file generated by [this tool](https://github.com/t4nz/ffmpeg-peaks) worked directly with wavesurfer. If we don't want to store peaks data, we could build a service that uses ffmpeg to return peaks on-demand. Note: it took 6.8s to generate a 7KB peak file for a 1h17m audio file.

**Comment by davidschober** [comment]
Move to close, we are now in progress.
