### ISSUE TITLE
Community work

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon-planning#261]

**Comment by adamjarling** [comment]
### Adam
5/14/2018
Accessibility 360 Audit Github issue mapping & refinement
https://wiki.duraspace.org/display/samvera/2018-05-14+Meeting+notes

5/15/2018
UX Interest Group Monthly Meeting
https://wiki.duraspace.org/display/samvera/2018-05-15+Meeting+notes

### Chris
Hyrax 2.1 release support and PR reviewing
Hyrax: 3070, 3077, 3080
ActiveTriples: 274

### Jen 
5/15/2018
Hyrax Metadata Ordering Working Group
https://wiki.duraspace.org/display/samvera/Hyrax+Metadata+Ordering+Call+2018-05-15
SMIG
https://wiki.duraspace.org/display/samvera/Metadata+Call+2018-05-22

### Julie 
5/15/2018
Hyrax Metadata Ordering Working Group
https://wiki.duraspace.org/display/samvera/Hyrax+Metadata+Ordering+Call+2018-05-15
SMIG 
https://wiki.duraspace.org/display/samvera/Metadata+Call+2018-05-22
Hyrax Descriptive Metadata Documentation and Assessment
https://wiki.duraspace.org/display/samvera/Documenting+and+Assessing+Metadata+in+Hyrax
