### ISSUE TITLE
Retro Notes - Sprint 152

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#265]

**Comment by jlhardes** [comment]
* manifest/player work was great!
* work type finally getting worked through!
    * still a lot to do but lots of progress
* manifest on fluorine feeding into player was cool to see and it’s available for anyone to try
* IIIF conference confusion about what was being demoed when; rapid movement on development also complicated making things demo-ready
    * more communication to test demo week before to make sure things are in good shape
    * Adam was ok with the last-minute demo pressure; others would prefer more time
    * if we know demo is going to happen, we need to plan better for it
    * needs discussion
* getting more into metadata stuff!
