### ISSUE TITLE
placeholder for encoding pipeline work

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#306]

**Comment by cjcolvar** [comment]
Besides https://github.com/samvera-labs/avalon-bundle/issues/102 and https://github.com/avalonmediasystem/avalon/issues/1863, I created tickets within active_encode directly: https://github.com/samvera-labs/active_encode/issues

**Comment by cjcolvar** [comment]
We decided to pull over these tickets totally 14 points:
https://github.com/samvera-labs/active_encode/issues/10
https://github.com/samvera-labs/active_encode/issues/11
https://github.com/samvera-labs/active_encode/issues/14
https://github.com/samvera-labs/active_encode/issues/16

@davidschober @mcwhitaker @joncameron Should we remove the estimate and close this ticket now?

**Comment by mcwhitaker** [comment]
I think we should do that, but also change the points on this to zero so we don't count the total twice when figuring out how many points we have completed in the sprint, which would drive the average up too much. @cjcolvar

**Comment by joncameron** [comment]
I've removed the points. Closing...
