### ISSUE TITLE
Write SamveraConnect 2018 workshop instructions

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon-planning#312]
Instructions to setup, tour, and use plugins (samvera-labs/avalon-bundle#214, samvera-labs/avalon-bundle#102).

Make sure to include environment setup (VirtualBox or personal dev machines?).

## Done looks like

- create workshop environment for run through 
- Instructions are written
- instructions edited

**Comment by davidschober** [comment]
I believe you all are working on this correct @cjcolvar? 

If so, can you drag it into in progress?

**Comment by cjcolvar** [comment]
No, we haven't really started on this yet.  We'll pull it over when we do...hopefully today.
