### ISSUE TITLE
Discuss permissions needs

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#333]
The total revamp of permissions and access control is not on the list of priorities for the general hyrax user institutions, so we need to look at our permissions needs to decide how we will proceed with this work. 

We can present to the broader hyrax community what we consider minimum functionality and how technically we think it can be accomplished. If we do this, we may be able to get other institutions interested in helping out with getting us there.

## Documents we currently have

Gap analysis: https://docs.google.com/spreadsheets/d/16oONQ8fSc-IoVBH9WouqBZN9WTOVbyZIFNPEvcE9nBs/edit#gid=1977787435

**Comment by davidschober** [comment]
we can wait for the Hyrax wg to see where they end up.

**Comment by joncameron** [comment]
After the meeting with Steve and Tom, we have two tasks: create a comprehensive accounting of permissions differences, and they might be reconciled, and then further discussion with Hyrax PO/Dev lead.
