### ISSUE TITLE
[Pawpaw] Mahler symphony doesn't play

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon-planning#370]
https://pawpaw.dlib.indiana.edu/media_objects/2j62s484w won't play due to an authorization error  from the streaming server.

This item is part of the sample collection and used for demo purposes so it should be able to play.

**Comment by rsteans** [comment]
Not limited to any one clip.  No audio is playing.  Video (Fete) is playing.

**Comment by rsteans** [comment]
time is stuck at 00:00.  Cannot move time slider.  Example:  https://pawpaw.dlib.indiana.edu/media_objects/c821gj76b

**Comment by cjcolvar** [comment]
Example of another audio item that isn't playing for the same reason.
https://pawpaw.dlib.indiana.edu/media_objects/9g54xh666

**Comment by phuongdh** [comment]
The streaming URLs shouldn't have `audio-only` in there. I fixed all wrong items and checked settings which look correct.
