### ISSUE TITLE
User Guide: how-to for the visual SME

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#401]
### Description
The User Guide needs instructions on how to use the visual Structural Metadata Editor.

### Done Looks like
- [x] Documentation written and reviewed
- [x] Documentation available on the Avalon wiki.

**Comment by joncameron** [comment]
Jen has a script that we could possibly use to generate these docs. 

"Prose-ification" is the key term here.

**Comment by joncameron** [comment]
Already done: https://wiki.dlib.indiana.edu/display/VarVideo/Visual+Structural+Metadata+Editor
