### ISSUE TITLE
Suggested Samvera Connect presentations

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#425]
- CircleCI - Chris + Collin - Workshop
- Avalon Turkey - Phuong + David - Lightning Talk
- ~Cloud Deployment - Phuong + Stanford (?) - Panel~
- Application  and Communities in Samvera - Avalon/Notch8/Ubiquity Press - Panel
- Community Building within Samvera Community - Jon D + David
- State of Avalon w/ Bruce Lee - Jon D + POs - Presentation
- Testing Front End with ReAct, Structural Metadata Editor - Adam + Dananji - Presentation
- Avalon Metadata in Hyrax, including BibImport - Julie + Jen - Presentation
- Product Management on/at/in Samvera, Products over Projects - Avalon Team - Panel
- NU Linked Data, Controlled Vocabs - Jen - Presentation
- Metadata IG Update - Julie - IG/WG Update
- Samvera Visioning Work - Carolyn - Presentation
- Accessibility in the Stack - Jon C - Panel
- Avalon Poster - Maria design - Poster
- Controlled Vocabs in Hyrax - Julie - Lightning Talk

**Comment by cjcolvar** [comment]
Embedding videos lessons learned - Chris - Lightning Talk

**Comment by jlhardes** [comment]
Submitted - Avalon Metadata in Hyrax, including BibImport - Julie + Jen - Presentation
