### ISSUE TITLE
Fix issues with timeliner-staging

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon-planning#565]
It seems some of the CSS is broken. As it's seen in the screenshot below, the main variations-app div doesn't span the entire height of the page. I can't reproduce it locally. Do you have any idea what might cause this in the staging server but not locally ?

![timeliner-staging.png](https://images.zenhubusercontent.com/5cc1d44fd0d0bb24e5be43b4/fd7fd79a-763a-4b26-9dec-fc8c41129957)

# Done
- [ ] Investigate issue with build/deploy to find why this is happening on the staging server

**Comment by Dananji** [comment]
I was able to reproduce this locally when I was working on another bug and pushed a CSS fix to the repo. This fix is on the `timeliner-staging` site.
