### ISSUE TITLE
Deploy all branches to Spruce

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-planning#7]
So that everyone can see what my branch looks like before I merge it to develop
- [ ] Figure out an URL scheme
- [ ] Configure Bamboo deploy plans

**Comment by davidschober** [comment]
Wait for Fedora 4

**Comment by joncameron** [comment]
This can happen at the beginning of Release 7.

**Comment by cjcolvar** [comment]
We don't use lancelot anymore so I'm changing the ticket name.

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon#2877
