### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon-planning#90]
### Description
One code review session, likely to be scheduled for the beginning of the 2nd swarm of this sprint.

### Done Looks Like
- [x] Code review session is scheduled and which code to review is decided upon.

**Comment by davidschober** [comment]
The team plans to handle this in swarm.

**Comment by cjcolvar** [comment]
We reviewed the work Valerie and I did on the ActiveEncode branch of hydra-derivatives:
https://github.com/projecthydra/hydra-derivatives/compare/active_encode_dev_con
